#!/bin/bash
#SBATCH -n 32 -c 64

#SBATCH --time=00:30:00

#SBATCH --qos=debug

#SBATCH --mail-type ALL
#SBATCH --mail-user td115@duke.edu

#SBATCH --constraint=haswell

#SBATCH --output /global/cscratch1/sd/%u/slurm/%x-%j.out
#SBATCH --error  /global/cscratch1/sd/%u/slurm/%x-%j.err

export PATH=$PATH:/usr/common/tig/taskfarmer/1.5/bin:$(pwd)
export THREADS=64

cd /global/homes/t/td115/running_coupling/JETSCAPE-Tequila/build
runcommands.sh task_list_dps/AuAu200/centrality20-30/Tequila_AuAu200_dp$1_tasks_list.txt
