#!/bin/bash
#SBATCH -n 24 -c 64

#SBATCH --time=10:00:00

#SBATCH --qos=regular

#SBATCH --mail-type ALL
#SBATCH --mail-user td115@duke.edu

#SBATCH --constraint=haswell

#SBATCH --output /global/cscratch1/sd/%u/slurm/%x-%j.out
#SBATCH --error  /global/cscratch1/sd/%u/slurm/%x-%j.err

export PATH=$PATH:/usr/common/tig/taskfarmer/1.5/bin:$(pwd)
export THREADS=32

cd /global/homes/t/td115/JETSCAPE3.4/JETSCAPE/build
runcommands.sh Tequila_PbPb2760_tasks_list.txt
